package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Build'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Build")) {
    check(artifactRules == "") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = "**/* => sources.zip"

    expectSteps {
        maven {
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            name = "Maven Build step"
            clearConditions()
        }
        insert(1) {
            maven {
                name = "Maven Build step (1)"
                id = "MavenNew"
                goals = "clean test"
                runnerArgs = "-Dmaven.test.failure.ignore=true"
            }
        }
        insert(2) {
            maven {
                name = "New build step"
                id = "Maven"
                goals = "clean test"
                runnerArgs = "-Dmaven.test.failure.ignore=true"
            }
        }
    }
}
